# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Konkursy Legnica
email: konkursy-legnica@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Strona poświęcona konkursom przeprowadzanym w ramach Roku mjr Władysława
  Dybowskiego w Legnicy. Zadaniem strony jest udzielanie szczegółowych informacji
  o wszystkich konkursach. Prezentowanie aktualności. Udostępnianie regulaminów,
  kart zgłoszeniowych, oraz materiałów multimedialnych związanych z konkursami.
  Zostaną tu również ogłoszone ich wyniki.
baseurl: "/stronka" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
filesurl: "/do-pobrania" #Tu znajdują się regulaminy, karty i inne pliki do pobrania.
imagesurl: "/img" #Tu obrazki będące częścią strony.
plasturl: "/plastyczny" #Tutaj są wszystkie podstrony związane z konkursem plastycznym.
plastdir: "/plastyczny/"
muzurl: "/muzyka-wykleta" #Tutaj wszystkie związane z Muzyką wyklętą.
muzdir: "/muzyka-wykleta/"
fbiconurl: "/fb_50.png" #Ikona facebooka.

target_blank: >-
  target="_blank"
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
